<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 2008/11/09 at 20:20:24
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$name = addslashes($_POST['name']);
@$confirmation_code = addslashes($_POST['confirmation_code']);
@$ecurrency_number = addslashes($_POST['ecurrency_number']);
@$email = addslashes($_POST['email']);

// Validation
//Sending Email to form owner
$pfw_header = "From: $email\n"
  . "Reply-To: $email\n";
$pfw_subject = "Receive confirmation code";
$pfw_email_to = "admin@cyberex.jp";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "name: $name\n"
. "confirmation_code: $confirmation_code\n"
. "ecurrency_number: $ecurrency_number\n"
. "email: $email\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

//Sending auto respond Email to visitor
$pfw_header = "From: admin@cyberex.jp\n"
  . "Reply-To: admin@cyberex.jp\n";
$pfw_subject = "Thanks for your notice item receive confirmation code";
$pfw_email_to = "$email";
$pfw_message = "Dear $name\n"
. "\n"
. "We review your item receive confirmation code to much as our record. and will sent other 50% of amount and all verification process will be completed\n"
. "\n"
. "To check your order status and transaction on this page\n"
. "\n"
. "https://cyberex.jp/tracking/\n"
. "\n"
. "\n"
. "Thanks and best regards\n"
. "\n"
. "+--------------------------------------+\n"
. "Escrow, Inc.\n"
. "Cyber Exchange Service Japan\n"
. "http://www.cyberex.jp/\n"
. "Japan E-gold Exchange Service\n"
. "http://www.e-goldex.jp/\n"
. "Phone: (+81)3-3835-3568\n"
. "Skype: e-goldex.jp  ICQ: 461063987\n"
. "+--------------------------------------+\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location: completed.htm");

?>
