<?php

# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.6 on 2010/07/17 at 19:39:38
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------
// Receiving variables
@$pfw_ip = $_SERVER['REMOTE_ADDR'];
@$Name = addslashes($_POST['Name']);
@$email = addslashes($_POST['email']);
@$ctl00cp1dlCateg = addslashes($_POST['ctl00$cp1$dlCateg']);
@$Account = addslashes($_POST['Account']);
@$Subject = addslashes($_POST['Subject']);
@$Comment = addslashes($_POST['Comment']);


$validator->validateGeneral('Your Name', $Name, _ERROR_FIELD_EMPTY);
$validator->validateGeneral('E-mail Address', $email, _ERROR_FIELD_EMPTY);
$validator->validateGeneral('Select Department', $ctl00cp1dlCateg, _ERROR_FIELD_EMPTY);
$validator->validateGeneral('Subject', $Subject, _ERROR_FIELD_EMPTY);
$validator->validateGeneral(' Question/Comment', $Comment, _ERROR_FIELD_EMPTY);
 if (count($validator->errors) == 0) {
     
 }

//Sending Email to form owner
$pfw_header = "From: $email\n"
        . "Reply-To: $email\n";
$pfw_subject = "Contact Form";
$pfw_email_to = "admin@e-globalcash.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
        . "Name: $Name\n"
        . "email: $email\n"
        . "ctl00cp1dlCateg: $ctl00cp1dlCateg\n"
        . "Account: $Account\n"
        . "Subject: $Subject\n"
        . "Comment: $Comment\n";
if (mail($pfw_email_to, $pfw_subject, $pfw_message, $pfw_header)) {
    $smarty->assign('success', true);
} else {
    $smarty->assign('success', FALSE);
    
}

header("Location: completad.htm");
?>
