<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.6 on 2010/03/03 at 20:22:49
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$Website = addslashes($_POST['Website']);
@$Description = addslashes($_POST['Description']);
@$Account = addslashes($_POST['Account']);
@$Name = addslashes($_POST['Name']);
@$email = addslashes($_POST['email']);
@$Messages = addslashes($_POST['Messages']);

// Validation
if (strlen($Website) == 0 )
{
header("Location: partners_error.htm");
exit;
}

if (strlen($Description) == 0 )
{
header("Location: partners_error.htm");
exit;
}

if (strlen($Account) == 0 )
{
header("Location: partners_error.htm");
exit;
}

if (strlen($Name) == 0 )
{
header("Location: partners_error.htm");
exit;
}

if (strlen($email) == 0 )
{
header("Location: partners_error.htm");
exit;
}

//Sending Email to form owner
$pfw_header = "From: $email\n"
  . "Reply-To: $email\n";
$pfw_subject = "Partner forms";
$pfw_email_to = "admin@e-globalcash.net";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "Website: $Website\n"
. "Description: $Description\n"
. "Account: $Account\n"
. "Name: $Name\n"
. "email: $email\n"
. "Messages: $Messages\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

//Sending auto respond Email to visitor
$pfw_header = "From: admin@e-globalcash.net\n"
  . "Reply-To: admin@e-globalcash.net\n";
$pfw_subject = "Thanks for your join our members";
$pfw_email_to = "$email";
$pfw_message = "Dear $Name\n"
. "\n"
. "Thanks for your join our certified partner and merchants members.\n"
. "\n"
. "We review your business description and will get back to you after on the listing in our pages\n"
. "\n"
. "Our Exchangers\n"
. "http://e-globalcash.net/index.php?page=exchangers\n"
. "\n"
. "Our Merchants\n"
. "http://e-globalcash.net/index.php?page=merchants\n"
. "\n"
. "Please make sure you have a reciprocal link on your website's index page BEFORE adding your listing. The e-Global Cash banners can be found here\n"
. "http://www.e-globalcash.net/partners.htm\n"
. "\n"
. "e-Global Cash Support Team";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location: partners_completad.htm");

?>
