<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 2008/09/27 at 15:14:41
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$name = addslashes($_POST['name']);
@$SentBank = addslashes($_POST['SentBank']);
@$SenderName = addslashes($_POST['SenderName']);
@$email = addslashes($_POST['email']);

// Validation
if (strlen($name) == 0 )
{
header("Location: error.htm");
exit;
}

if (strlen($SenderName) == 0 )
{
header("Location: error.htm");
exit;
}

if (strlen($email) == 0 )
{
header("Location: error.htm");
exit;
}

//Sending Email to form owner
$pfw_header = "From: $email\n"
  . "Reply-To: $email\n";
$pfw_subject = "Paid report Domestic deposit in Japan";
$pfw_email_to = "cyberexjp@gmail.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "name: $name\n"
. "SentBank: $SentBank\n"
. "SenderName: $SenderName\n"
. "email: $email\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

//Sending auto respond Email to visitor
$pfw_header = "From: cyberexjp@gmail.com\n"
  . "Reply-To: cyberexjp@gmail.com\n";
$pfw_subject = "Your order process has been Approved !!";
$pfw_email_to = "$email";
$pfw_message = "Dear $name\n"
. "\n"
. "We review check in our bank account. \n"
. "after your money received completed, will sent e-gold within 24 hours.\n"
. "\n"
. "To check your order status and transaction on this page\n"
. "\n"
. "https://cyberex.jp/tracking/\n"
. "\n"
. "\n"
. "Thanks and best regards\n"
. "\n"
. "+--------------------------------------+\n"
. "Cyber Exchange Service Japan\n"
. "http://www.cyberex.jp/\n"
. "+--------------------------------------+";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location: completed.htm");

?>
