<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 2008/09/27 at 18:39:53
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$name = addslashes($_POST['name']);
@$MTCN = addslashes($_POST['MTCN']);
@$AccountName = addslashes($_POST['AccountName']);
@$SendLocation = addslashes($_POST['SendLocation']);
@$address = addslashes($_POST['address']);
@$Phone = addslashes($_POST['Phone']);
@$email = addslashes($_POST['email']);

// Validation
if (strlen($name) == 0 )
{
header("Location: error.htm");
exit;
}

if (strlen($MTCN) == 0 )
{
header("Location: error.htm");
exit;
}

if (strlen($AccountName) == 0 )
{
header("Location: error.htm");
exit;
}

if (strlen($SendLocation) == 0 )
{
header("Location: error.htm");
exit;
}

if (strlen($email) == 0 )
{
header("Location: error.htm");
exit;
}

//Sending Email to form owner
$pfw_header = "From: $email\n"
  . "Reply-To: $email\n";
$pfw_subject = "Paid report Western Union";
$pfw_email_to = "admin@cyberex.jp";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "name: $name\n"
. "MTCN: $MTCN\n"
. "AccountName: $AccountName\n"
. "SendLocation: $SendLocation\n"
. "address: $address\n"
. "Phone: $Phone\n"
. "email: $email\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

//Sending auto respond Email to visitor
$pfw_header = "From: admin@cyberex.jp\n"
  . "Reply-To: admin@cyberex.jp\n";
$pfw_subject = "Your order process has been Approved !!";
$pfw_email_to = "$email";
$pfw_message = "Dear $name\n"
. "\n"
. "We review check in our bank account. \n"
. "after your money received completed, will sent your request e-currency within 3 business day.\n"
. "\n"
. "To check your order status and transaction on this page\n"
. "\n"
. "https://cyberex.jp/tracking/\n"
. "\n"
. "\n"
. "Thanks and best regards\n"
. "\n"
. "+--------------------------------------+\n"
. "Cyber Exchange Service Japan\n"
. "http://www.cyberex.jp/\n"
. "+--------------------------------------+\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location: completed.htm");

?>
