<?php
	// define database tables predefine name	
	define("_TABLE_PREFIX",'');
	define('_TABLE_SESSIONS',_TABLE_PREFIX.'sessions');
	define('_TABLE_CONFIGURATIONS',_TABLE_PREFIX.'configuration');	
	define('_TABLE_CONFIGURATION_GROUPS',_TABLE_PREFIX.'configuration_group');		
	define('_TABLE_ADMINS',_TABLE_PREFIX.'admins');
	define('_TABLE_EMAILTEMPLATES',_TABLE_PREFIX.'emailtemplates');
	define('_TABLE_EMAILTEMPLATES_DESCRIPTION',_TABLE_PREFIX.'emailtemplates_description');
	define('_TABLE_INFO_TEMPLATES',_TABLE_PREFIX.'info_templates');
	define('_TABLE_FAQS',_TABLE_PREFIX.'faqs');	
	define('_TABLE_NEWS',_TABLE_PREFIX.'news');
	define('_TABLE_LANGUAGES',_TABLE_PREFIX.'languages');
	define('_TABLE_FAQS',_TABLE_PREFIX.'faqs');
	define('_TABLE_FAQS_DESCRIPTION',_TABLE_PREFIX.'faqs_description');		
	define('_TABLE_USERS',_TABLE_PREFIX.'users');
	define('_TABLE_API_CONFIGS',_TABLE_PREFIX.'api_configs');
	define('_TABLE_COUNTRIES',_TABLE_PREFIX.'countries');
	define('_TABLE_MESSAGES',_TABLE_PREFIX.'messages');
	define('_TABLE_SECURITY_QUESTIONS',_TABLE_PREFIX.'security_questions');	
	define('_TABLE_SECURITY_QUESTIONS_DESCRIPTION',_TABLE_PREFIX.'security_questions_description');	
	define('_TABLE_ZONES',_TABLE_PREFIX.'zones');
	define('_TABLE_CURRENCIES',_TABLE_PREFIX.'currencies');
	define('_TABLE_USER_BALANCE',_TABLE_PREFIX.'user_balance');
	define('_TABLE_USER_WALLET',_TABLE_PREFIX.'user_wallet');
	define('_TABLE_TRANSACTIONS',_TABLE_PREFIX.'transactions');
	define('_TABLE_TRANSACTIONS_HISTOTY',_TABLE_PREFIX.'transactions_history');
	define('_TABLE_USER_SETTINGS',_TABLE_PREFIX.'user_information_settings');
?>